version: "3.6"

services:
  mysql8:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: haolee
      MYSQL_PASSWORD: haolee
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  mysql57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: haolee
      MYSQL_PASSWORD: haolee
    volumes:
      - ./mysql57-data:/docker-entrypoint-initdb.d
    ports:
      - 3305:3306
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  postgres14:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    command: [--auth]
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_USERNAME=haolee
      - MONGO_PASSWORD=haolee
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/log:/var/log/mongodb
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  rabbitmq:
    image: rabbitmq:3.11.16-management
    hostname: rabbit
    container_name: "rabbitmq3.11.16"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
